name: WorldManagement
main: me.koledogcodes.worldcontrol.WorldControl
version: 2.1
commands:
  worldcontrol:
    description: General command for WorldControl.
    aliases: [wc, worldc, wcontrol]
  wc-import:
    description: General command for WorldControlImport.
  wc-gen:
    description: General command for WorldControlGenerator.
    aliases: [wcgen, wcg]