name: WorldManagement
main: me.koledogcodes.worldcontrol.WorldControl
version: 1.3
commands:
  worldcontrol:
    description: General command for WorldControl.
    aliases: [wc, worldc, wcontrol]