package me.koledogcodes.worldcontrol.api;

public enum MessageType {
	
	PLACE_BLOCK_DENY,
	BREAK_BLOCK_DENY,
	PLAYERLIMIT_DENY,
	PLAYER_CMD_DENY,
	PLAYER_CHAT_DENY,
	PLAYER_WHITELIST_DENY,
	PLAYER_INTERACT_DENY,
	PLAYER_WORLD_PERMISSION_DENY,
	PLAYER_EAT_DENY,
	ALTERNATE_WORLD_DENY,
	NETHER_TELEPORT_DENY
	
}
